// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rndivcsonsojgelzewkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZGl2Y3NvbnNvamdlbHpld2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzEwNTksImV4cCI6MjA3NDA0NzA1OX0.N4_RL-IclVLuTmAhoHRZvSgNfNKfivLg5mS2_rgNtuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});